# Generated by Django 3.2.7 on 2021-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_follower_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='owner_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
