# Generated by Django 3.2.7 on 2021-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210909_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(default='https://avatars.githubusercontent.com/u/74496363?v=4'),
        ),
    ]
